# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Mohammadreza Daviran"
title_separator          : "-"
name                     : &name "Mohammadreza Daviran"
description              : &description "M.Sc. student in Computing Science at University of Alberta. Research in Data Management, NLP, LLMs, and Text-to-SQL."
url                      : "https://mmdrez4.github.io"
baseurl                  : "" 
repository               : "mmdrez4/mmdrez4.github.io"

# Site Author (sidebar)
author:
  avatar           : "profile_2.jpg"
  name             : "Mohammadreza Daviran"
  # pronouns         : "he/him"
  bio              : "M.Sc. student in Computing Science at University of Alberta. \n Research in Data Management, NLP, LLMs, and Text-to-SQL."
  location         : "Edmonton, Canada"
  employer         : "University of Alberta"
  uri              : "https://www.ualberta.ca/en"
  email            : "mohammadrezadaviran01@gmail.com"

  # Academic profiles
  # googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  # arxiv            : "https://arxiv.org/abs/2508.07087"
  orcid            : # add if you register one
  researchgate     : # optional
  scopus           : # optional
  pubmed           : # not needed unless you publish biomedical papers

  # Code repositories
  github           : "mmdrez4"

  # Social media
  linkedin         : "mohammadreza-daviran"
  twitter          : # optional if you want X/Twitter
  bluesky          : # optional if you have a bsky handle

# Publication Category
publication_category:
  books:
    title: "Books"
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"

# Site Settings
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               : false

atom_feed:
  hide                   : false
  path                   :

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : 
facebook:
  username               :
og_image                 :
og_description           :
social:
  type                   : "Person"
  name                   : "Mohammadreza Daviran"
  links:
    - "https://github.com/mmdrez4"
    - "https://www.linkedin.com/in/mohammadreza-daviran/"
    - "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
    - "https://arxiv.org/abs/2508.07087"

# Analytics
analytics:
  provider               : false

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/Edmonton

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
