# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mohammadreza Daviran
title: B.Sc Student in Computer Engineering at Sharif University of Technology
email: mohammadrezadaviran01@gmail.com
website: www.mohammadrezadaviran.me
# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  mmdrez4
stackoverflow_username: "12349022"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: mmdrez4
linkedin_username: mohammadreza-daviran
huggingface_username: mmdrez4

# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: CV
#   icon: fas fa-download
#   url: https://drive.google.com/file/d/18W7Tjp_FENdLj0BL_U-5pBBy0sTqhFo8/view?usp=share_link


# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Greetings! I am Mohammadreza Daviran, recently I got my degree in Computer Engineering at <a href="https://en.sharif.edu/">Sharif University of Technology</a>,
  which is renowned as a leading educational institution in Iran and the Middle East.
  At the moment, I am actively engaged in the development of a Persian open-source Wordnet. 
  Notably, The paper for this project will be submitted to the Language Resources and Evaluation Journal. 
  Additionally, I am engaging in a substantial and pioneering project to create a Persian Large Language Model.
  Furthermore, One of my strong fascinations lies in the applications of Natural Language Processing (NLP) and Machine Learning within the healthcare sector. As a testament to this passion,
  you can access the preprint of our paper, "A Novel Approach to Persian Medical and Drug Question-Answering Utilizing Large Language Models", through <a href="https://openreview.net/forum?id=ER-6OuoaNY">this</a> link.
  
  My fields of interest are:
  
  - Natural Language Processing 

  - Machine Learning

  - ML for Health

  - Large Language Models
  
  - Multimodal Deep Learning
  
  - Modern Information Retrieval
  
  - Bioinformatics
  

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: NLP and DH Lab
        link: http://language.ml/
        # link_text: boringcompany.com
        sub_title: Research Assistant
        caption: November 2022 - Present
        quote: >
          A Comprehensive Toolkit for NLP and Information Retrieval: Tackling Linguistic Challenges in Both Persian and English.
        description: | # this will include new lines to allow paragraphs
            Since commencing my research at the NLP and DH lab, my focus has been on two primary endeavors. Firstly, I have dedicated my efforts to the creation of an open-source Persian Wordnet. Simultaneously, I have actively participated in the development of a Persian/English medical question-answering model that leverages the power of Large Language Models.| 
            In addition to these projects, I have been deeply involved in a noteworthy initiative aimed at pioneering the development of a Persian Large Language Model (LLM). This undertaking has been carried out in close collaboration with three esteemed professors, further emphasizing the significance of our research efforts.
      
      # - layout: left
      #   title: Sharif University of Technology
      #   link: https://en.sharif.edu
      #   # link_text: boringcompany.com
      #   sub_title: Research Assistant
      #   caption: September 2021 - July 2022
      #   quote: >
      #     Image Processing and Facial Image Analysis
      #   description: | # this will include new lines to allow paragraphs
      #       In my research endeavors, I've ventured into the dynamic field of facial image analysis with two distinct yet interconnected focuses. The first revolves around leveraging Graph Convolutional Networks (GCN) to predict linkages between face images, streamlining the process of grouping images portraying the same individual. Simultaneously, I've explored a novel approach, treating face clustering as a pairwise classification task, training a classifier to directly discern whether two faces should be categorized within the same class. These multifaceted efforts collectively represent my dedication to advancing the capabilities of facial recognition and clustering, promising innovative solutions that could redefine the landscape of this critical area of study.

      - layout: left
        title: Artificial Intelligence for Better Health
        link: https://commamed.com/
        # link_text: boringcompany.com
        sub_title: Intern
        caption: July 2022 - Sep 2022
        quote: >
          Image Processing for Healthcare applications
        description: | # this will include new lines to allow paragraphs
            In my research and practical experience, I have engaged in a multifaceted exploration of computer vision and machine learning applications. This journey encompasses training a model for the precise segmentation of lungs from X-Ray images, a critical task in medical image analysis. Additionally, I have delved into the development and deployment of Convolutional Neural Networks (CNNs) and Fully Connected models for image classification, showcasing my proficiency in crafting deep learning solutions. Furthermore, my expertise extends to advanced domains such as transfer learning, Generative Adversarial Networks (GANs), image processing techniques, and statistical analysis—all of which play pivotal roles in my efforts to advance artificial intelligence and machine learning applications.


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Awesome NLP and Information Retrieval
        link: https://github.com/mmdrez4/awesome-nlp/
        # link_text: Project Website
        additional_links:
          - title:  mmdrez4/awesome-nlp
            icon: fab fa-github
            url: https://github.com/mmdrez4/awesome-nlp/
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A Comprehensive Toolkit for NLP and Information Retrieval: Tackling Linguistic Challenges in Both Persian and English.
        description: | # this will include new lines to allow paragraphs
          The "Awesome NLP Projects for Persian and English" GitHub repository is a curated collection focusing on Natural Language Processing (NLP) and Information Retrieval for both Persian and English languages.
          It features eight distinct projects that tackle various challenges such as question answering, bias detection, illegal word filtering, sentiment analysis, and information retrieval across medical and social media data.
          Each project is self-contained, offering its own documentation and code for implementation, making it a valuable resource for researchers and practitioners in the NLP and Information Retrieval domains.
      
      
      - layout: top-middle
        title: Stock Price Prediction
        link: https://github.com/mmdrez4/stock_price_prediction/
        # link_text: Project Website
        additional_links:
          - title:  mmdrez4/stock_price_prediction
            icon: fab fa-github
            url: https://github.com/mmdrez4/stock_price_prediction/
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Achieving financial insight and efficiency through TinyML: Empowering Raspberry Pi for real-time stock price prediction and automated trading
        description: | # this will include new lines to allow paragraphs
          In this project, I developed and deployed an LSTM (Long Short-Term Memory) model powered by TinyML on a Raspberry Pi. The primary objective was to enable real-time stock price prediction and automated trading while prioritizing compact and low-power solutions. 

          
      - layout: top-middle
        title: Microarray Data Analysis for Leukemia
        link: https://github.com/mmdrez4/Bioinformatics_AML_Genes/
        # link_text: Project Website
        additional_links:
          - title:  mmdrez4/Bioinformatics_AML_Genes
            icon: fab fa-github
            url: https://github.com/mmdrez4/Bioinformatics_AML_Genes/
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Unlocking the Genetic Mysteries of Leukemia: A Comprehensive Analysis of Microarray Data through GEO Database and R Language.
        description: | # this will include new lines to allow paragraphs
          In this project, I harnessed the power of a GEO (Gene Expression Omnibus) database to conduct a comprehensive analysis of microarray data, specifically focusing on Leukemia, a form of blood cell cancer. I leveraged the R programming language to perform advanced data analysis and gain valuable insights into the molecular underpinnings of this disease. 
      
      # - layout: top-middle
      #   title: Profile Matching Based Face Identification
      #   link: https://github.com/mmdrez4/ProfileMatching
      #   # link_text: Project Website
      #   additional_links:
      #     - title:  mmdrez4/ProfileMatching
      #       icon: fab fa-github
      #       url: https://github.com/mmdrez4/ProfileMatching
      #     # - title:  Github page for project (eg. sproogen/modern-resume-theme)
      #     #   icon: fab fa-github
      #     #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
      #   quote: >
      #     Fostering Digital Connection: Innovating User Profile Matching Across Diverse Social Networks through Face Identification.
      #   description: | # this will include new lines to allow paragraphs
      #     I both implemented and summarized the paper titled 'User Profiles Matching for Different Social Networks Based on Face Identification.' In addition to this, I crafted a user profiles matching model customized for distinct social networks, making use of face identification datasets.


      - layout: top-middle
        title: Digital Currency Fluctuation
        link: https://github.com/mmdrez4/mobile-programming
        # link_text: Project Website
        additional_links:
          - title:  mmdrez4/mobile-programming
            icon: fab fa-github
            url: https://github.com/mmdrez4/mobile-programming
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Empowering Users with Real-Time Insights: An Android Application for Monitoring Digital Currency Fluctuations Through Live Streaming.
        description: | # this will include new lines to allow paragraphs
          In this endeavor, I created an Android application dedicated to monitoring real-time digital currency fluctuations via live streaming. This project reflects my proficiency in mobile app development and a keen interest in the dynamic world of digital currencies, offering users a convenient and accessible tool for staying informed about market changes and trends.



  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sharif University of Technology
        caption: 2019 - 2024
        sub_title: BSc Computer Engineering
        quote: >
          Established in 1966, Sharif University is the best higher education institution in Iran according to QS ranking, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the Iran but also the Middle East.
        description: | # this will include new lines to allow paragraphs
          While at Sharif University of Technology, I honed many of the foundational skills that have been integral to my career, including effective teamwork and meeting tight deadlines. My university experience was immensely rewarding, and it was during this time that I gained valuable insights into maintaining a healthy work-life balance.

          Additionally, I devoted a significant portion of my free time to being an active committee member of the Sharif Cognitive Sciences Community (Shenasa), where I assumed roles such as lecturer and presenter. This involvement allowed me to further develop my communication and presentation abilities while also contributing to the academic community.
  
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Machine Learning and Natural Language Processing, some of my other interests and hobbies are:
      - Compose critiques for movies and music
      - Playing Soccer and Basketball
      

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
